
<!----------------------------------------------->
<!--            AFFICHAGE ERREURS              -->
<!----------------------------------------------->

  </TD>
</TR>

<TR>
  <TD class="MESSAGE">

    <?php
      // affichage des messages d'alerte
      echo "<H2>".$footer_msg."</H2>" ;
      // affichage du bon ou mauvais envoi de mail
      echo "<H2>".$msg_mail."</H2>" ;
    ?>
          
  </TD>
</TR>

<!----------------------------------------------->

